// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ILogger is an autogenerated mock type for the ILogger type
type ILogger struct {
	mock.Mock
}

// Error provides a mock function with given fields: message
func (_m *ILogger) Error(message string) {
	_m.Called(message)
}

type mockConstructorTestingTNewILogger interface {
	mock.TestingT
	Cleanup(func())
}

// NewILogger creates a new instance of ILogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewILogger(t mockConstructorTestingTNewILogger) *ILogger {
	mock := &ILogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
