// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// IUserHandler is an autogenerated mock type for the IUserHandler type
type IUserHandler struct {
	mock.Mock
}

// Login provides a mock function with given fields: c
func (_m *IUserHandler) Login(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIUserHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewIUserHandler creates a new instance of IUserHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIUserHandler(t mockConstructorTestingTNewIUserHandler) *IUserHandler {
	mock := &IUserHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
