// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Gym-Apps/gym-backend/models"
	mock "github.com/stretchr/testify/mock"

	request "github.com/Gym-Apps/gym-backend/dto/request"

	response "github.com/Gym-Apps/gym-backend/dto/response"
)

// IUserService is an autogenerated mock type for the IUserService type
type IUserService struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, userLoginRequest
func (_m *IUserService) Login(ctx context.Context, userLoginRequest request.UserLoginDTO) (response.UserLoginDTO, error) {
	ret := _m.Called(ctx, userLoginRequest)

	var r0 response.UserLoginDTO
	if rf, ok := ret.Get(0).(func(context.Context, request.UserLoginDTO) response.UserLoginDTO); ok {
		r0 = rf(ctx, userLoginRequest)
	} else {
		r0 = ret.Get(0).(response.UserLoginDTO)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, request.UserLoginDTO) error); ok {
		r1 = rf(ctx, userLoginRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, userRegisterRequest
func (_m *IUserService) Register(ctx context.Context, userRegisterRequest request.UserRegisterDTO) (response.UserRegisterDTO, error) {
	ret := _m.Called(ctx, userRegisterRequest)

	var r0 response.UserRegisterDTO
	if rf, ok := ret.Get(0).(func(context.Context, request.UserRegisterDTO) response.UserRegisterDTO); ok {
		r0 = rf(ctx, userRegisterRequest)
	} else {
		r0 = ret.Get(0).(response.UserRegisterDTO)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, request.UserRegisterDTO) error); ok {
		r1 = rf(ctx, userRegisterRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetPassword provides a mock function with given fields: ctx, _a1, _a2
func (_m *IUserService) ResetPassword(ctx context.Context, _a1 models.User, _a2 request.UserResetPasswordDTO) error {
	ret := _m.Called(ctx, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.User, request.UserResetPasswordDTO) error); ok {
		r0 = rf(ctx, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIUserService interface {
	mock.TestingT
	Cleanup(func())
}

// NewIUserService creates a new instance of IUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIUserService(t mockConstructorTestingTNewIUserService) *IUserService {
	mock := &IUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
